### ISSUE TITLE
Ony Line - The Great Masquerade

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#116]
Name:  Dhanae
Account Name (for vote points rewards): Skylark
Map & Area: Stormwind Keep
How to replicate the bug: die during the event
What happens: if you get aggro and die you should be able to speak to Squire Rowe to restart it but you can't and Windsor's corpse stays outside SW gates.
What should happen: You should be able to speak to Squire Rowe to restart the event
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 

Extra Information: Myself, Dris and Vainzki did this, vainzki abandoned it to try to get it again from the squire but he still wouldnt talk to him.  Also when Lady Prestor changed into the Ony form, it wasn't ony  but a small dragonkin caster.

**Comment by scotty0100** [comment]
Can you retry this? I was able to re obtain the quest. Please let me know if you are able to now as it has been a while.

**Comment by Skylark14** [comment]
I think the script corruption you had a while ago may have been the culprit, however not sure if we have any near that part so will have to ask.

**Comment by scotty0100** [comment]
This works now it can just take a while for it to reset.

To change the skin to Onyxia's skin we need to find a video/image that clearly shows this quest having Onyxia's skin as I've been told my the classic developers that they clearly remember the dragokin caster skin being used so that you only saw Onyxia in her Lair.

It was then changed in TBC to be Onyxia.

**Comment by scotty0100** [comment]
Please reopen if we have raw sources.
