### ISSUE TITLE
NPC - Spell: Silithid Pox

### ISSUE THREAD

**Issue by Skylark14** [scotty0100/wowascension-issues#150]
Name: Dhanae
Account Name (for vote points rewards): Rothk
Map & Area: Un'Goro
How to replicate the bug: get infected
What happens: get infected from a bug, player reported it was showing as 40% damage  taken increase
What should happen:  it should only give a 10% damage taken increase
Located on WoWHead Map (if applicable):
Source (proof, if applicable): 
http://db.valkyrie-wow.com/?spell=8137

Extra Information:

**Comment by scotty0100** [comment]
Seems this scales with level. Which is why the description isn't quite right on wowhead DB's. 

Level 1 = 10%
Level 60 = 50%

And looking at the comments on wowhead:

http://www.wowhead.com/spell=8137/silithid-pox#comments

It seems like it was quite high before. Blizzard seem to reduce the length of the debuff in future patches. But this seems to be working as intended ATM?
