### ISSUE TITLE
Theramore - Temporary lock up

### ISSUE THREAD

**Issue by Bilbo79** [scotty0100/wowascension-issues#501]
Name: Ocholoco
Account Name: Bilbo79
Map & Area:  Theramore, inside the castle walls.  Anywhere
How to replicate the bug:   Walk around for a while in Theremore.
What happens:

a)  It does not matter what you are doing, but it is best reproduced if you are interacting with an NPC.  While leveling a new toon, I was able to reproduce this 5-6 times.  You could be anywhere in the area (Inn, Castle, Mage keep, armor smith, etc).  It will hit everything and everyone in the area.  And the area is large, but it seems restricted to the confines of the city walls.

The game will simply go to 1 FPS or less.  Then, after about 20 seconds or so, it releases you, and you are good to go again.

I have money that says that there is a patrol unit (or something that moves) in Theramore that is glitching out that part of the zone.   Adjust his patrol route.  Or get him out of the earth,wall,whatever that is causing this.

What should happen:

a)  It shouldn't happen.

Located on WoWHead Map (if applicable): Theramore
Source (proof, if applicable): Personal Experience

Extra Information:

**Comment by kamicolo** [comment]
https://github.com/scotty0100/wowascension-issues/issues/96

1 NPC Guard Patrol is causing this issue. 

I'll elaborate:
The server has a folder called "mmaps" active. This contains information where as example: People or NPC's can or cannot walk. The regarding NPC has 1 waypoint with bad coordinates. At those coordinates it will actually fall off from the world but, mmaps is trying to prevent this as it's not possible it will however autocorrect the guard and push him out again. Due to this Database vs mmaps collision a memory crash occurs which leads to a "FPS" drop.

Also Dev's are having a fight regarding this:
1. Adjust the core coding and bypass the normal set of rules (My opinion: Don't bypass core due reason 2).
2. Enter correct x,y and z positions in the DataBase (this then won't occur but, there are "ALOT" of NPC's causing this and they are very difficult to spot aside from that the question remains if "any NPC and or critter etc. is causing this issue aswell on "Random" movement either "bad spawn coordinates or the coding regarding random movement can conflict with mmaps in certain areas)
